web:
 image: metabase/metabase
 ports:
 - "3000:3000"
 links:
 - dbmetabase
 

dbmetabase:
 image: library/postgres
 ports:
 - "5432:5432"
 environment:
 - POSTGRES_PASSWORD=klapaucius
 - POSTGRES_DB=metabase_db
 - POSTGRES_USER=meta


dbadmin:
 image: lukasmartinelli/pgstudio
 ports:
 - "8080:8080"
 links:
 - dbmetabase
